using System.ComponentModel.DataAnnotations;
using Todo.Api.Controllers.Dto.TodoItem;

namespace Todo.Api.Controllers.Dto.Group;

/// <summary>
/// This DTO is used for creating a new group. This does not include the Id property, as it is generated by the database.
/// Represents the data structure sent from clients when creating a new Group.
/// </summary>
public class CreateGroupDto
{
    /// <summary>
    /// Gets or sets the name of the Group.
    /// </summary>
    [Required]
    [MaxLength(200)]
    public string Name { get; set; } = "";
}